# Common
device: 0
seed: 2026

# Training
train_model: models/yolov8n.pt
train_project: runs/train
train_name: exp
data_yaml: datasets/train_val_data.yaml
epochs: 100
imgsz: 1024
batch: 16

# Prediction
predict_model: runs/train/exp/weights/best.pt
predict_project: runs/predict
predict_name: exp
data_folder: datasets/images/test
sample_csv: datasets/sample_submission.csv
output_csv: submit.csv
conf: 0.25
iou: 0.7
save_txt: false
save_conf: false
save_result: false
